### ISSUE TITLE
Discussion about the IK process

### ISSUE THREAD

**Issue by Carmenw1203** [jjjj1504/mmd_vmd_interpolation#1]
Thank you for your great work. It's interesting and helpful!
However, I'm curious whether the IK process is necessary when you interpolate the motion frames?

**Comment by jjjj1504** [comment]
Hi, @Carmenw1203 

As you mentioned https://github.com/jjjj1504/mmd_vmd_interpolation/issues/1#issue-1858794707

> whether the IK process is necessary when you interpolate the motion frames?

1. Sorry, I'm not sure I get your meaning about "IK process is necessary".

    1. Did you mean "motion data of IK bones (`左足IK`, `右足IK`) in MMD"?

    2. Could you explain it with some examples (scenario) or references (which part of code or README documentation)?

    3. Is this what you are referring to? [`README.md#L53`](https://github.com/jjjj1504/mmd_vmd_interpolation/blob/364fc33/README.md?plain=1#L53)

        > <ins>Calculate the bone position</ins> in dancing motion vmd file, and export bone position <ins>without orientation</ins> to "nonrotatable bone motion" vmd file. In this way, camera view won't be swung along bone rotation while we let camera follow certain bone of dancing model in mmd camera mode.

    4. Or did you wonder "whether <ins>inverse kinematics</ins> is considered in this project"?

        1. No, I didn't process any inverse kinematics.
        2. Honestly speaking,
            1. I haven't mastered the mechanism of inverse kinematics in MMD.
            2. I don't know how to interpolate motion data with inverse kinematics constraints.  
               For example, how to guarantee that hand moves freely and smoothly without any singularity of rotation of arm and elbow?

2. By the way, maybe it's because I'm an MMDer, my main concern is to ensure whether the interpolated <ins>***camera***</ins> motion frames work fine in MMD.

3. Besides, in this project
    1. I didn't process any inverse kinematics.
    2. There's a process of interpolating bones motion data into 30 fps by MMD way (`Interpolation curve` or `補間曲線操作`): [`generate_nonrotatable_bones_data.py#L95`](https://github.com/jjjj1504/mmd_vmd_interpolation/blob/364fc33/tools/generate_nonrotatable_bones_data.py#L95)  
       That is, if the interpolation curves of bone motion data are not set properly in MMD, velocity continuity of the interpolation result among the given frames won't be guaranteed.

**Comment by Carmenw1203** [comment]
Thank you for your detailed reply! My mainly concern is about the inverse kinematics process and maybe I should refer to some official document of MMD or source code to know more about the  inverse kinematics process in MMD. Thanks again for your patient answer.

**Comment by jjjj1504** [comment]
Hi, @Carmenw1203 

As you mentioned https://github.com/jjjj1504/mmd_vmd_interpolation/issues/1#issuecomment-1749311958

> I should refer to some official document of MMD or source code to know more about the inverse kinematics process in MMD.

1. Official documents posted on [VPVP](https://sites.google.com/view/vpvp/) seem not free. Besides, I'm not so sure whether the details of inverse kinematics in mmd are explained in those documents or not.

1. According to [Wikipedia](https://en.wikipedia.org/wiki/MikuMikuDance#Overview), the source code of MMD isn't released ...

    > *Despite this, the source code has not been released, and the developer has no intentions of doing so, making it impossible for people to continue building upon the original software.*

1. Or you could refer to the source code of related projects. I found some related inverse kinematics programs below. *However, I'm unsure whether those programs meet the mechanism in MMD. You could check with developers.*

    1. elect-gombe / `k210_mmd`: `bonelist::update1ik` in [`skeletal-animation.hpp#L215`](https://github.com/elect-gombe/k210_mmd/blob/v0.1.0/skeletal-animation.hpp#L215).

    2. miu200521358 / `vmd_sizing`: `c_calc_IK` in [`MServiceUtils.pyx#L20`](https://github.com/miu200521358/vmd_sizing/blob/ver5.01.08/src/utils/MServiceUtils.pyx#L20)
